### ISSUE TITLE
3.0c_433+_v5.audio and t64 files

### ISSUE THREAD

**Issue by Flupper** [markusC64/1541ultimate2#1]
I just updated from 2.6k to 3.0c_433+_v5.audio and loading of t64 files seems to be gone.

**Comment by markusC64** [comment]
Just checked official revisions 417 and revisions 424: The directory software/filetype does not contain an entry filetype_crt.cc, so it cannot work. Firmware 2.x contained a software/filemanager/filetype_crt.cc.

So this has nothing to do with the improvements, but with the firmware 3.0.

**Comment by Flupper** [comment]
Sorry you're right, official 3.0 r417 for II-2 (not +) has the same issue.
Reverted back to 2.6k and all is good again.

**Comment by markusC64** [comment]
No problem. You've made me aware of the missing feature.

**Comment by markusC64** [comment]
An improved 2.6k is being prepared. You can expect the following inprovements:

+ Fix 8K and ultimax
+ Fix loading retro replay crt
+ Business Basic, simons' basic, comal80 and westermann modules support
+ GeoRAM support
+ Retro Replay updated

incl. Fixes from David Horrocks and KCS Support from Rene Garcia.

**Comment by Flupper** [comment]
Cool thanks,
Will there be an audio version without 2 drives ?

**Comment by markusC64** [comment]
Yes, there will be. Currently I am looking for testers to have it tested before release.

**Comment by Grrrolf** [comment]
Using the 3.0 firmware I have no problems with .t64 files and can run files that are inside this container. Do not use the contextual menu, but use cursor to the left to enter the .t64 container. Then select the file you'd like to start en select run.

This is what you meant, right?

**Comment by markusC64** [comment]
Indeed, t64 files are working this way.
