### ISSUE TITLE
Mapping Ultimate Audio - a visual problem? Or did it break?

### ISSUE THREAD

**Issue by Grrrolf** [markusC64/1541ultimate2#12]
Hi there, 

I noticed this (I hope) visual problem with enabling/disabling the Ultimate-Audio-mapping configuration introduced in the 3.1d_20171224+_v1 release of the firmware.
I have made screenshots of it since pictures say more than words ;-)

![image](https://user-images.githubusercontent.com/10052794/35115357-2a2c0e32-fc88-11e7-8b5e-6c25d24ebb9a.png)

**Comment by markusC64** [comment]
The new release contains the bugfix.
