### ISSUE TITLE
Ulticopy not working

### ISSUE THREAD

**Issue by AmonRA** [markusC64/1541ultimate2#2]
Ulticopy doesn't start the copy of a real disk in 1571 (Drive ID 9) to an image .d64 on the 1541U2 (Drive ID 8).

Steps to reproduce 

1. Set 1571 to Device ID 9 via the jumper on the back
2. Connect 1571 to C64, and connect 1541U2 to 1571 (interface port)
3. Put the original floppy in the 1571. Browse to a location on your SD card or USB stick to save the new d64 file to. Press F5 and select Ulticopy 9 (because 1571 is the source).
4. The reading of the floppy doesn't start...

Flashing the 1541U2 back to 1541u2_3.0_417 resolves the issue.

**Comment by markusC64** [comment]
Thanks for your bug report.

Cf. http://www.1541ultimate.net/content/index.php?option=com_issueform&bug=227

BTW: Revision 423 from Gideon introduced that bug.

**Comment by markusC64** [comment]
Fixed in Revision 460 by Gideon.

**Comment by markusC64** [comment]
Feel free to use the just released version 3.0f_460+_v1.
