### ISSUE TITLE
I need training....

### ISSUE THREAD

**Issue by Pontiac76** [markusC64/1541ultimate2#21]
Not a bug, or an issue, but, something I'm really confused about.

In the same day I received two notifications about the U2+ firmware being updated.  

One points to https://github.com/markusC64/1541ultimate2/releases/tag/v3.4c
The other to https://github.com/markusC64/1541ultimate2/releases/tag/v3.5

Now, I get that these are different releases/tags/versions.  That's absolutely clear.  What isn't clear to me is that if 3.5 is out, is that specifically for the U64 since the only assets to that tag seems to be for the U64?  Is the U2+ still on 3.4c?

In the 3.5 tag, I don't see anything for the U2+.  This is my Ultimate Confusion.

**Comment by markusC64** [comment]
Gideon did not release the firmware 3.5 for 1541 Ultimate - and he probably won't do 'cause the has released 3.5a today. Again only for Ultimate 64 up to now.

Quite probably I'll add a rebuild form the sources for the missing targets. But not now, you see, that versions require some testing.

**Comment by markusC64** [comment]
BTW: 1541 Ultimate II+ might follow earlier than the 1541 Ultimate II. You see, the former has an excelent recovery system, so that the risk is much less.
