### ISSUE TITLE
1541 U II+ ( REU disabled starting .crt images )

### ISSUE THREAD

**Issue by ciccior2003** [markusC64/1541ultimate2#27]
I have tested that starting ( without flashing ) any type of .crt the REU go off.
To renable the Reu when the .crt image is runing it is possible changing any settings in sub-menu ( C64 AND CARTRIDGE SETTINGS ) for example changing the "cpu adds valid after phi2" ( saving or not new settings ).
It would be perfect if the REU stayed on starting .crt images.

Thnaks

**Comment by Pontiac76** [comment]
Maybe I'm missing something here, but is that a thing for real machines?
The REU is a cartridge (Virtual or otherwise), and you're attempting to
load another cartridge on top of that.  I know there were cartridge
expanders, but you could only have one cartridge selected at a time.

**Comment by kribjo** [comment]
VICE as well as some physical expanders allow the simultaneous use of
multiple cartridges (under certain conditions, and with various issues
likely depending on the setup).

See (for example):
https://www.hackup.net/2018/06/c64-expansion-port-expander-research/
https://vice-emu.sourceforge.io/vice_7.html#SEC107
https://retrocomputing.stackexchange.com/questions/12450/which-cartridges-were-typically-used-together-on-commodore-64-systems
https://www.lemon64.com/forum/viewtopic.php?t=71988&sid=2a69fa6552d7435eab2f0bd45cbab1af

**Comment by markusC64** [comment]
Certainly it would be better to have this feature request on gideon's github. But anyway, Gideon is planing to rewrite cartridge handling in one of the next versions. In the old implementation I am quite sure we both say: Won't fix.

For the announced rewrite of cartridge handling, that should be tested again.

**Comment by markusC64** [comment]
I gave seen you've posted this issue on Gideon's github. So closing it here.
