### ISSUE TITLE
SIDPLAY64 U2 CMD not working on 3.9

### ISSUE THREAD

**Issue by TomCat666** [markusC64/1541ultimate2#30]
On 3.9 1541u2+ the SIDPLAY64 for U2 CMD interface - sidplay64-reu-1541u2cmd.prg  (https://sourceforge.net/projects/sidplay64/) does not load SID files anymore. You get an error each time you try to load a SID file through it.
Also first file or directory is not displayed anymore in the filelist, instead an empty file is shown.
Everything working fine with 3.7 firmware.

**Comment by markusC64** [comment]
Gideon knows about that problem. And he has already fixed it. You can try https://github.com/GideonZ/ultimate_releases/blob/master/latest_unofficial_u2p.zip which contains the fix.

**Comment by TomCat666** [comment]
Thank you. Working perfectly, both issues fixed in the latest_unofficial 3.9a.
