### ISSUE TITLE
1541U-II stopped responding after running Updater ver. 3.10

### ISSUE THREAD

**Issue by Andrea6128** [markusC64/1541ultimate2#31]
Hi, I have a **1541U-II** (not +) with fw 3.9. I downloaded and triggered a new fw 3.10 update (file **update_3.10_au.u2u**). It went good, but after a question  "_About to flash? Yes/No_" (before the flash process) I accidentally answered "_No_". The C64 then asked to turn off. I turned it off and on again and since that the 1541U-II doesn't respond on the middle button. The only reset button works. I tried to find any solution on the Internet but I wasn't lucky. The recovery mode (holding middle button then turning the C64 on) doesn't work (asi I suppose it's the 1541U-II+ feature only). It seems that the Updater software has a bug that shows on a specific hardware. Is there any workaround how to solve this problem? Thanks :)

**Comment by markusC64** [comment]
Thats interesting - there is no 1541 Ultimate II (without plus) firmware 3.9, because it is too large to fit in flash. There is some 3.9 alpha version that fitted in flash, though.

Recovery mode is a 1541 Ultimate II+ only feature.

Depending what the bug caused to be overwritten, there might be a recovery by placing a "ultimate.bin" with the right content on the micro sd card... We'll investigate.

**Comment by markusC64** [comment]
Confirmed - that will kill the 1541 Ultimate II. Please do not try.

I think I have seen in the source code what I need to know. Quite probable, placing "ultimate.bin" on micro sd card will help.

**Comment by markusC64** [comment]
[u2-lite-recover-3.9-and-older.zip](https://github.com/markusC64/1541ultimate2/files/6887690/u2-lite-recover-3.9-and-older.zip)

Instructions for recovery:

1st) Copy the attached "ultimate.bin" on an Micro SD Card.
2nd) Place at least one 1541 Ultimate II Updater on the same Micro SD Card.
3rd) Insert the Micro SD Card in the 1541 Ultimate II and power on your C64
4th) You should find the 1541 Ultimate II mostly working, not everything might work, but it should be enough to run a firmware updater.
5th) Remember not to use the 1541 Ultimate II with the "ultimate.bin" placed on the SD card, so either remove the SD Card, delete the "ultimate.bin" file or rename it.

**Comment by Andrea6128** [comment]
Thanks. Yes, the 3.9 was alpha.
I received another solution from Gideon, though. The workaround was simplier:

1. download and rename the desired firmware (3.10 audio in my case) to "recover.u2u"
2. copy it onto a blank microSD card and put it into the 1541U-II
3. boot the C64, the updater starts flashing new fw
4. when done, turn off C64, remove microSD and delete "recover.u2u" for normal work

That worked for me. 
Anyway it's good to know there's a solution you suggested.
