### ISSUE TITLE
Ultima 6 doesn't load with firmware 3.0f 456 v2 but Ultima 6 works on 3.0 107 firmware

### ISSUE THREAD

**Issue by megaman85** [markusC64/1541ultimate2#4]
Ultima 6 doesn't load with firmware 3.0f 456 v2 but Ultima 6 works on 3.0 107 firmware. After typing in: LOAD"*",8,1 it is stuck on a black screen load indefinitely for NTSC Commodore 64, 64c and C128.

However Ultima 6 works fine for firmware 3.0 107 and 3.0c firmeware.

You use the program disk (Disk 1) to load up the game.
[Ultima 6.zip](https://github.com/markusC64/1541ultimate2/files/852226/Ultima.6.zip)

**Comment by markusC64** [comment]
Thanks for your bug report. I'll check whether this my my bug or Gideon's.

Please note that I only have PAL devices available...

**Comment by markusC64** [comment]
Feel free to test Version 3.0f_460+_v1.

And check if you have disabled modules, REU, second emulated floppy, iec device and son on.

**Comment by megaman85** [comment]
yes! Ultima VI works on 3.0f_460+_v1 firmware on my UII+!

**Comment by markusC64** [comment]
Well, then I'm closing this issue, but without discussion lock; if problems come back, you can leave a note here.
