### ISSUE TITLE
Middle Button on UII and UII+ crashes and hard locks the c128 when running certain programs

### ISSUE THREAD

**Issue by megaman85** [markusC64/1541ultimate2#5]
For instance, when running Compute's Gazette SID Player 128,

For boot up the d64 file
Then you see a blue screen
Wait until you see the Rainbow Colored SID Player screen,
8 out of 10 times the computer would lock up when you press the middle button at this point.

This only happens on the C128 running C128 program while pressing the middle button on the UII and UII+.

See screenshots
![17352297_10208431686490111_7766935840372516851_n](https://cloud.githubusercontent.com/assets/26499399/24070054/d0beaf82-0b72-11e7-87c5-bfd86b733031.jpg)
![17353632_10208431690330207_7640262953859904649_n](https://cloud.githubusercontent.com/assets/26499399/24070056/d0da4314-0b72-11e7-8a5c-033519fcfec3.jpg)
![17353238_10208431691690241_5171510161368195917_n](https://cloud.githubusercontent.com/assets/26499399/24070057/d0da4ad0-0b72-11e7-9b8d-8dd7e499a7be.jpg)
![17309352_10208431694210304_3031898945340016404_n](https://cloud.githubusercontent.com/assets/26499399/24070055/d0d9c376-0b72-11e7-87e2-b02375d32171.jpg)
![17342927_10208431697570388_672661616507246432_n](https://cloud.githubusercontent.com/assets/26499399/24070058/d0db5fc4-0b72-11e7-8b16-9efde551db7d.jpg)

I have a similar issue with Ultima V for the C128, it too locks up when pressing the middle button on the UII and UII+, during disk swap or during the game.

These issues do not occur on a real c64 or C128 in c64 mode running Sid Player 64 and Ultima V.

What could be causing this?

This problem happens on 3.0 107 firmware and 3.0f 456v2 firmware for UII and 3.0c and 3.0f 456 v2 firmware for UII+.

**Comment by markusC64** [comment]
I have had the same issue on my C128 with Geos 64 / 128. Adjusting PHI2 values (both) on the "C64 settings" helped.

**Comment by megaman85** [comment]
so what settings did u use?

**Comment by markusC64** [comment]
Well, that settings are device dependent. Note I've a PAL C128.

Anyway, my settings: CPU Addr valid after PHI2 100ns, PHI2 edge recovery enabled.

**Comment by megaman85** [comment]
Are you using Ultimate II+? I have a Ultimate II+ rev A.

I don't see 100ns, 

I see 16ns, 32ns, 48ns, 64ns, 80ns,96ns, 112ns,120ns
I tried all the PHI2 and Edge PHI2 Recovery settings,

but the middle button sometimes work and sometimes it doesn't,

what do you think is the issue?

**Comment by megaman85** [comment]
[Compute!'s Gazette Sid Player (19xx)(Compute!).d64.zip](https://github.com/markusC64/1541ultimate2/files/852632/Compute.s.Gazette.Sid.Player.19xx.Compute.d64.zip)

**Comment by megaman85** [comment]
[Ultima5.zip](https://github.com/markusC64/1541ultimate2/files/852635/Ultima5.zip)

**Comment by markusC64** [comment]
No, I'm using Ultimate II+ on my C64 and Ultimate II without Plus on my C128.

**Comment by megaman85** [comment]
I tried 80, 100, 120,140,160 ns
with and without phi edge 2 recovery
and 160ns seems to be the most stablest when pressing the middle button,

but when playing Ultima V in c128 mode,
the middle button works when asked to swap disks during creating a character,
after I create a character, and journey onwards, and save the game by pressing q ,

it asks to insert the Britannia disk,

so I press the middle button to switch to Brittannia disk,

next it asks for the Dwelling disk,

and I press the middle button again and it locks up, this always happens here while doing this
![img_0707](https://cloud.githubusercontent.com/assets/26499399/24075330/3f42b8e6-0bd6-11e7-8c02-bd9be078fead.JPG)

can test Ultima V on your C128 and create a character and then journey onwards,
and press q to save, and insert Britannia disk and then swap to dwelling disk and see
if it locks up for you too?
