### ISSUE TITLE
Shimmering screen on C128 when running Retro Replay on UII and UII+

### ISSUE THREAD

**Issue by megaman85** [markusC64/1541ultimate2#6]
When using Retro Replay on C128 on UII and UII+, the screen shimmers if power down and power up.

See video, and ignore the rolling, thats from my iPhone camera.

When using Retro Replay on C128 on UII and UII+, the screen doesn't shimmer if power down and power up with the commodore key press down on start up.

This happens on C128 on UII with 3.0 107 and 3.0f 456v2 firmware and UII+ on firmware 3.0c and 3.0f.
[shimmering.mp4.zip](https://github.com/markusC64/1541ultimate2/files/852232/shimmering.mp4.zip)

This doesn't happen on a C64, only the C128

**Comment by Flexmaen** [comment]
What's your PHI2 value? It is 80ns by default, if I set it to 120ns the 1541U runs a lot more stable on my C128. Maybe you could try this.

**Comment by megaman85** [comment]
I tried 120ns PHI2 value on my NTSC C128 and it still shimmers unless I press the commodore key to boot directly into c64 mode when using Retro Replay.

Currently I am using 112ns PHI2 value on my NTSC C128 and UII+ as that is more stable for my C128 , especially when running Slipstream in C64 in which it will crash will 120ns PHI2 value setting but runs fine with 112ns.
