### ISSUE TITLE
dual drive firmware U2+

### ISSUE THREAD

**Issue by Grrrolf** [markusC64/1541ultimate2#8]
Hi there Markus,

I noticed that when using drive B of the dual drive firmware on the U2+, the drive leds are off while using drive B. I used a physical drive for device 8 and used drive b as on device 9.  I tested this on firmware 3.0g_466+_v1 and did not try any earlier firmware.

I have not tested this on the U2, but it will probably show the same behaviour.
Yours,

Rolf

**Comment by markusC64** [comment]
Well, neither the 1541 U2 nor the 1541 U2+ have extra leds for the second drive. So I assume that this is on purpose by Gideon.

**Comment by Grrrolf** [comment]
Ok, thanx. It's trivial anyway. I closed this issue.
